### ISSUE TITLE
Evaluación profesores Iván e Isabel

### ISSUE THREAD

**Issue by MARTABLANCOORTE** [Adalab/modulo-1-evaluacion-final-MARTABLANCOORTE#25]
Esto ya no me corresponde a mi jeje ;) Os dejo a vosotros esa ardua labor, espero que el "Readme.md" y este Project Board os sea de ayuda. 

Muchas gracias! :)

pd: al final no he podido arreglar los problemas Isa :(

**Comment by igarrido-adalab** [comment]
Eres una crack Marta!
Nos ha encantado tu README.md (parece un cuaderno de bitácora) y esta issue dedicada a las profes ha sido la guinda del pastel!

Lo hemos compartido con las otras profes, como ejemplo de "ojo como se lo ha currado esta chica".
